### ISSUE TITLE
Setting up phase fails at "npm run build", "npm run watch" and "npm start"

### ISSUE THREAD

**Issue by v95** [reddit/reddit-mobile#149]
I just forked this project and attempted to set up the environment according to the provided instructions in the Readme file. However, I have been getting several errors as I follow each and every step.

**Here is the console output for "npm run build" command:**

    [22:05:38] Using gulpfile ~\Documents\GitHub\reddit-mobile\gulpfile.js
    [22:05:38] Starting 'default'...
    [22:05:38] Starting 'clean'...
    [22:05:38] Finished 'clean' after 8.98 ms
    [22:05:38] Starting 'assets'...
    [22:05:38] Finished 'assets' after 18 ms
    [22:05:38] Starting 'prod-js'...
    [22:05:38] Starting bundle...
    [22:05:38] Starting 'prod-less'...
    [22:05:38] Finished 'prod-less' after 8.75 ms
    Note: The code generator has deoptimised the styling of "C:/Users/v95/Documents/GitHub/reddit-mobile/node_modules/jquery/dist/jquery.js" as it exceeds the max of "100KB".
    Note: The code generator has deoptimised the styling of "C:/Users/v95/Documents/GitHub/reddit-mobile/node_modules/reddit-text-js/node_modules/snuownd/snuownd.js" as it exceeds the max of "100KB".
    Note: The code generator has deoptimised the styling of "C:/Users/v95/Documents/GitHub/reddit-mobile/node_modules/reddit-text-js/node_modules/sanitize-html/node_modules/lodash/dist/lodash.js" as it exceeds the max of "100KB".
    Note: The code generator has deoptimised the styling of "C:/Users/v95/Documents/GitHub/reddit-mobile/node_modules/lodash/index.js" as it exceeds the max of "100KB".
    Note: The code generator has deoptimised the styling of "C:/Users/v95/Documents/GitHub/reddit-mobile/node_modules/gsap/src/uncompressed/TweenMax.js" as it exceeds the max of "100KB".
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: Cannot find module 'reddit-mobile/src/views/components/Listing' from 'C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\reddit-mobile-plugin-ads\views\components'
        at C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
        at process (C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
        at ondir (C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
        at load (C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
        at onex (C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
        at C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
        at FSReqWrap.oncomplete (fs.js:95:15)

    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
    npm ERR! node v0.12.3
    npm ERR! npm  v2.9.1
    npm ERR! code ELIFECYCLE
    npm ERR! reddit-mobile@1.4.6 build: `gulp`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the reddit-mobile@1.4.6 build script 'gulp'.
    npm ERR! This is most likely a problem with the reddit-mobile package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     gulp
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls reddit-mobile
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\v95\Documents\GitHub\reddit-mobile\npm-debug.log

**Here is the console output for "npm run watch" command:**

    > reddit-mobile@1.4.6 watch C:\Users\v95\Documents\GitHub\reddit-mobile
    > gulp watch

    [22:08:28] Using gulpfile ~\Documents\GitHub\reddit-mobile\gulpfile.js
    [22:08:28] Starting 'watch'...
    [22:08:28] Starting 'watchless'...
    [22:08:28] Finished 'watchless' after 28 ms
    [22:08:28] Starting 'watchjs'...
    [22:08:28] Starting bundle...
    Note: The code generator has deoptimised the styling of "C:/Users/v95/Documents/GitHub/reddit-mobile/node_modules/jquery/dist/jquery.js" as it exceeds the max of "100KB".
    Note: The code generator has deoptimised the styling of "C:/Users/v95/Documents/GitHub/reddit-mobile/node_modules/reddit-text-js/node_modules/snuownd/snuownd.js" as it exceeds the max of "100KB".
    Note: The code generator has deoptimised the styling of "C:/Users/v95/Documents/GitHub/reddit-mobile/node_modules/reddit-text-js/node_modules/sanitize-html/node_modules/lodash/dist/lodash.js" as it exceeds the max of "100KB".
    Note: The code generator has deoptimised the styling of "C:/Users/v95/Documents/GitHub/reddit-mobile/node_modules/lodash/index.js" as it exceeds the max of "100KB".
    Note: The code generator has deoptimised the styling of "C:/Users/v95/Documents/GitHub/reddit-mobile/node_modules/gsap/src/uncompressed/TweenMax.js" as it exceeds the max of "100KB".
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: Cannot find module 'reddit-mobile/src/views/components/Listing' from 'C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\reddit-mobile-plugin-ads\views\components'
        at C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
        at process (C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
        at ondir (C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
        at load (C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
        at onex (C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
        at C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
        at FSReqWrap.oncomplete (fs.js:95:15)

    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
    npm ERR! node v0.12.3
    npm ERR! npm  v2.9.1
    npm ERR! code ELIFECYCLE
    npm ERR! reddit-mobile@1.4.6 watch: `gulp watch`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the reddit-mobile@1.4.6 watch script 'gulp watch'.
    npm ERR! This is most likely a problem with the reddit-mobile package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     gulp watch
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls reddit-mobile
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\v95\Documents\GitHub\reddit-mobile\npm-debug.log

**Here is the console output for "npm start" command:**

    > reddit-mobile@1.4.6 start C:\Users\v95\Documents\GitHub\reddit-mobile
    > node --harmony index.js

    module.js:338
        throw err;
        ^
    Error: Cannot find module 'reddit-mobile/src/views/components/Listing'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (C:/Users/v95/Documents/GitHub/reddit-mobile/node_modules/reddit-mobile-plugin-ads/views/components/Ad.jsx:4:32)
        at Module._compile (module.js:460:26)
        at normalLoader (C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\babel\node_modules\babel-core\lib\babel\api\register\node.js:150:5)
        at Object.require.extensions.(anonymous function) [as .jsx] (C:\Users\v95\Documents\GitHub\reddit-mobile\node_modules\babel\node_modules\babel-core\lib\babel\api\register\node.js:163:7)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)

    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
    npm ERR! node v0.12.3
    npm ERR! npm  v2.9.1
    npm ERR! code ELIFECYCLE
    npm ERR! reddit-mobile@1.4.6 start: `node --harmony index.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the reddit-mobile@1.4.6 start script 'node --harmony index.js'.
    npm ERR! This is most likely a problem with the reddit-mobile package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node --harmony index.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls reddit-mobile
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\v95\Documents\GitHub\reddit-mobile\npm-debug.log

I'd be happy to provide more information, so please let me know.

**Comment by ajacksified** [comment]
It appears that you either haven't run `npm link` from within `reddit-mobile` (to help out with circular dependencies with plugins), or if you have, you don't have your NODE_PATH set up properly to look for `reddit-mobile`, which should be linked from the global npm directory.

**Comment by v95** [comment]
Hi ajacksified,

You're right, I checked the environment variables and NODE_PATH wasn't there. I have added it and everything seems to be compiling fine now. Thanks!

**Comment by ajacksified** [comment]
Great!
